using System.Net;
using System.Text;
using ThreatMonster.Core.Analysis;
using ThreatMonster.Core.Model;
using ThreatMonster.Core.Stride;
using static ThreatMonster.Core.Reports.ReportContext;

namespace ThreatMonster.Core.Reports;

/// <summary>
/// A self-contained, printable HTML report. Use the browser's "Save as PDF" to get a PDF.
/// </summary>
public static class HtmlReport
{
    public static string Generate(ThreatModel model)
    {
        var ctx = new ReportContext(model);
        var s = model.Summary;
        var sb = new StringBuilder();

        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">")
          .Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
          .Append("<title>").Append(E(s.Title)).Append(" – Threat model report</title><style>").Append(Css).Append("</style></head><body>");

        sb.Append("<header><p class=\"eyebrow\">Threat model report</p><h1>").Append(E(s.Title)).Append("</h1><dl class=\"meta\">");
        Meta(sb, "Owner", s.Owner);
        Meta(sb, "Reviewer", s.Reviewer);
        Meta(sb, "Contributors", s.Contributors.Count > 0 ? string.Join(", ", s.Contributors) : null);
        Meta(sb, "Last modified", s.ModifiedAt?.ToString("yyyy-MM-dd"));
        Meta(sb, "Generated", DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm"));
        sb.Append("</dl>");
        if (!string.IsNullOrWhiteSpace(s.Description)) sb.Append("<p class=\"lead\">").Append(Multiline(s.Description)).Append("</p>");
        sb.Append("</header>");

        AppendSummary(sb, ctx);

        foreach (var diagram in model.Diagrams)
        {
            sb.Append("<section class=\"diagram\"><h2>").Append(E(diagram.Title)).Append("</h2>");
            if (!string.IsNullOrWhiteSpace(diagram.Description)) sb.Append("<p>").Append(Multiline(diagram.Description)).Append("</p>");
            sb.Append("<figure>").Append(SvgDiagram.Render(diagram, model.Threats)).Append("</figure>");

            foreach (var target in ctx.Targets(diagram))
            {
                var threats = ctx.ThreatsFor(target.Id).ToList();
                if (threats.Count == 0 && !target.OutOfScope)
                    continue;
                sb.Append("<article class=\"target\"><h3>").Append(E(target.Name)).Append(" <span class=\"kind\">").Append(target.Kind).Append("</span></h3>");
                if (target.OutOfScope)
                    sb.Append("<p class=\"oos\">Out of scope").Append(string.IsNullOrWhiteSpace(target.OutOfScopeReason) ? "" : ": " + E(target.OutOfScopeReason)).Append("</p>");
                foreach (var t in threats)
                    AppendThreat(sb, t);
                sb.Append("</article>");
            }
            sb.Append("</section>");
        }

        if (ctx.Findings.Count > 0)
        {
            sb.Append("<section><h2>Open analysis points</h2><ul class=\"findings\">");
            foreach (var f in ctx.Findings)
                sb.Append("<li class=\"").Append(f.Level == FindingLevel.Warning ? "warn" : "info").Append("\">").Append(E(f.Message)).Append("</li>");
            sb.Append("</ul></section>");
        }

        sb.Append("<footer>Generated by ThreatMonster</footer></body></html>");
        return sb.ToString();
    }

    static void AppendSummary(StringBuilder sb, ReportContext ctx)
    {
        var threats = ctx.Model.Threats;
        sb.Append("<section><h2>Summary</h2><div class=\"cards\">");
        Card(sb, "Threats", threats.Count, "");
        Card(sb, "Open", threats.Count(t => t.Status == ThreatStatus.Open), "open");
        Card(sb, "Mitigated", threats.Count(t => t.Status == ThreatStatus.Mitigated), "mitigated");
        Card(sb, "Accepted", threats.Count(t => t.Status == ThreatStatus.Accepted), "");
        Card(sb, "High / critical open", threats.Count(t => t.Status == ThreatStatus.Open && t.Severity >= Severity.High), "critical");
        sb.Append("</div>");

        if (threats.Count == 0)
        {
            sb.Append("<p>No threats have been recorded yet.</p></section>");
            return;
        }

        // STRIDE x severity matrix of open threats.
        var severities = new Severity?[] { Severity.Critical, Severity.High, Severity.Medium, Severity.Low, null };
        sb.Append("<h3>Open threats by category</h3><table class=\"matrix\"><thead><tr><th>Category</th>");
        foreach (var sev in severities) sb.Append("<th>").Append(sev?.ToString() ?? "Not rated").Append("</th>");
        sb.Append("<th>Total</th></tr></thead><tbody>");
        foreach (var cat in StrideRules.All)
        {
            var open = threats.Where(t => t.Category == cat && t.Status == ThreatStatus.Open).ToList();
            sb.Append("<tr><th>").Append(CategoryLabel(cat)).Append("</th>");
            foreach (var sev in severities)
            {
                var n = open.Count(t => t.Severity == sev);
                sb.Append("<td class=\"").Append(n > 0 ? SevClass(sev) : "zero").Append("\">").Append(n).Append("</td>");
            }
            sb.Append("<td><b>").Append(open.Count).Append("</b></td></tr>");
        }
        sb.Append("</tbody></table>");

        sb.Append("<h3>All threats</h3><table class=\"list\"><thead><tr><th>#</th><th>Threat</th><th>Target</th><th>Category</th><th>Severity</th><th>Status</th></tr></thead><tbody>");
        foreach (var t in threats.OrderByDescending(t => t.Severity ?? (Severity)(-1)).ThenBy(t => t.Number))
        {
            sb.Append("<tr><td>").Append(t.Number).Append("</td><td><a href=\"#t").Append(t.Number).Append("\">").Append(E(t.Title)).Append("</a></td><td>")
              .Append(E(ctx.TargetName(t.TargetId))).Append("</td><td>").Append(CategoryLabel(t.Category)).Append("</td><td>")
              .Append(SeverityBadge(t)).Append("</td><td>").Append(StatusBadge(t.Status)).Append("</td></tr>");
        }
        sb.Append("</tbody></table></section>");
    }

    static void AppendThreat(StringBuilder sb, Threat t)
    {
        sb.Append("<div class=\"threat\" id=\"t").Append(t.Number).Append("\"><div class=\"threat-head\"><span class=\"num\">#").Append(t.Number)
          .Append("</span><strong>").Append(E(t.Title)).Append("</strong><span class=\"badges\"><span class=\"badge cat\">").Append(CategoryLabel(t.Category))
          .Append("</span>").Append(SeverityBadge(t)).Append(StatusBadge(t.Status)).Append("</span></div>");
        if (t.Cvss is not null)
            sb.Append("<p class=\"cvss\">CVSS ").Append(CvssLabel(t)).Append(" <code>").Append(E(t.Cvss.Vector)).Append("</code></p>");
        if (!string.IsNullOrWhiteSpace(t.Description))
            sb.Append("<p>").Append(Multiline(t.Description)).Append("</p>");
        if (!string.IsNullOrWhiteSpace(t.Mitigation))
            sb.Append("<p class=\"mitigation\"><b>Mitigation:</b> ").Append(Multiline(t.Mitigation)).Append("</p>");
        sb.Append("</div>");
    }

    static void Meta(StringBuilder sb, string label, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
            sb.Append("<div><dt>").Append(label).Append("</dt><dd>").Append(E(value)).Append("</dd></div>");
    }

    static void Card(StringBuilder sb, string label, int value, string cls) =>
        sb.Append("<div class=\"card ").Append(cls).Append("\"><span class=\"value\">").Append(value).Append("</span><span class=\"label\">").Append(label).Append("</span></div>");

    static string SeverityBadge(Threat t) =>
        $"<span class=\"badge {SevClass(t.Severity)}\">{SeverityLabel(t)}{(t.Cvss is null ? "" : " " + CvssLabel(t))}</span>";

    static string StatusBadge(ThreatStatus s) => $"<span class=\"badge st-{s.ToString().ToLowerInvariant()}\">{StatusLabel(s)}</span>";

    static string SevClass(Severity? s) => s is null ? "sev-none" : "sev-" + s.Value.ToString().ToLowerInvariant();

    static string E(string? text) => WebUtility.HtmlEncode(text ?? "");

    static string Multiline(string text) => E(text.Trim()).Replace("\r", "").Replace("\n", "<br>");

    const string Css = """
        :root { --fg:#1c1917; --muted:#57534e; --line:#e7e5e4; --bg:#fff; --soft:#fafaf9; --accent:#7c3aed; }
        * { box-sizing: border-box; }
        body { font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; color: var(--fg); background: var(--bg); max-width: 1000px; margin: 0 auto; padding: 32px 24px; }
        h1 { font-size: 30px; margin: 0 0 12px; } h2 { font-size: 21px; margin: 40px 0 12px; padding-bottom: 6px; border-bottom: 2px solid var(--line); }
        h3 { font-size: 16px; margin: 24px 0 8px; }
        .eyebrow { text-transform: uppercase; letter-spacing: .08em; font-size: 12px; color: var(--accent); font-weight: 600; margin: 0; }
        .meta { display: flex; flex-wrap: wrap; gap: 4px 24px; margin: 0 0 12px; } .meta dt { font-size: 12px; color: var(--muted); } .meta dd { margin: 0; font-weight: 500; }
        .lead { color: var(--muted); font-size: 15px; }
        .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; }
        .card { border: 1px solid var(--line); border-radius: 10px; padding: 12px 16px; background: var(--soft); }
        .card .value { display: block; font-size: 26px; font-weight: 700; } .card .label { color: var(--muted); font-size: 13px; }
        .card.open .value { color: #b45309; } .card.mitigated .value { color: #15803d; } .card.critical .value { color: #b91c1c; }
        table { border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 13px; }
        th, td { border-bottom: 1px solid var(--line); padding: 6px 8px; text-align: left; vertical-align: top; }
        thead th { background: var(--soft); font-weight: 600; }
        .matrix td { text-align: center; } .matrix td.zero { color: #d6d3d1; }
        a { color: inherit; }
        figure { margin: 12px 0; border: 1px solid var(--line); border-radius: 10px; padding: 8px; } figure svg { max-width: 100%; height: auto; display: block; margin: 0 auto; }
        .target { break-inside: avoid-page; } .kind { font-weight: 400; color: var(--muted); font-size: 13px; }
        .threat { border: 1px solid var(--line); border-left: 4px solid var(--accent); border-radius: 8px; padding: 10px 14px; margin: 8px 0; break-inside: avoid; }
        .threat-head { display: flex; flex-wrap: wrap; gap: 8px; align-items: baseline; } .num { color: var(--muted); font-variant-numeric: tabular-nums; }
        .badges { margin-left: auto; display: flex; gap: 6px; flex-wrap: wrap; }
        .badge { display: inline-block; border-radius: 999px; padding: 1px 9px; font-size: 12px; font-weight: 500; background: #f5f5f4; white-space: nowrap; }
        .badge.cat { background: #ede9fe; color: #5b21b6; }
        .sev-critical { background: #fee2e2; color: #991b1b; } .sev-high { background: #ffedd5; color: #9a3412; }
        .sev-medium { background: #fef9c3; color: #854d0e; } .sev-low { background: #dbeafe; color: #1e40af; } .sev-none { background: #f5f5f4; color: #57534e; }
        .st-open { background: #fef3c7; color: #92400e; } .st-mitigated { background: #dcfce7; color: #166534; }
        .st-accepted { background: #e0e7ff; color: #3730a3; } .st-notapplicable { background: #f5f5f4; color: #57534e; }
        .mitigation { background: #f0fdf4; border-radius: 6px; padding: 6px 10px; } .cvss code { font-size: 12px; }
        .oos { color: var(--muted); font-style: italic; }
        .findings li.warn::marker { content: "⚠ "; } .findings li { margin: 2px 0; }
        footer { margin-top: 48px; color: var(--muted); font-size: 12px; text-align: center; }
        @media print { body { padding: 0; max-width: none; } h2 { break-after: avoid; } section.diagram { break-before: page; } a { text-decoration: none; } }
        """;
}
